/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author Débora Alves
 */
public class Genio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Genio.class.getName());

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
        lblFrase.setText("<html>Vou pensar em um valor entre 1 e 5. Tente adivinhar..</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVal = new javax.swing.JSpinner();
        ptnPalpite = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Paulo\\Documents\\NetBeansProjects\\prg03deboraasantos\\src\\main\\java\\br\\com\\ifba\\atividade04\\images\\genie.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Paulo\\Documents\\NetBeansProjects\\prg03deboraasantos\\src\\main\\java\\br\\com\\ifba\\atividade04\\images\\lamp.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        lblFrase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFrase.setForeground(new java.awt.Color(255, 255, 255));
        lblFrase.setText("Frase");
        lblFrase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\João Paulo\\Documents\\NetBeansProjects\\prg03deboraasantos\\src\\main\\java\\br\\com\\ifba\\atividade04\\images\\speech-bubble (2).png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtVal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        ptnPalpite.setText("Palpite");
        ptnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptnPalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(ptnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel5.setText("Valor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ptnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptnPalpiteActionPerformed
        // TODO add your handling code here:

        // Gera um número aleatório entre 1 e quase 6 (não inclui o 6)
        double n = 1 + Math.random() * (6 - 1);
         int valor = (int) n;// Converte o número aleatório para inteiro
      
        // Pega o número digitado pelo usuário no campo Spinner
         int num = Integer.parseInt(txtVal.getValue().toString());
         String f1 = "<html>Parabéns, você acertou !!</html>";
         String f2 = "<html>Errou! eu pensei no valor " + valor + "</html>";
         
        // Se o número sorteado for igual ao escolhido, mostra f1; caso contrário, f2
         String res = (valor == num)?f1:f2;
         
        // Exibe a mensagem no rótulo da tela
         lblFrase.setText(res);
    }//GEN-LAST:event_ptnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Genio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JButton ptnPalpite;
    private javax.swing.JSpinner txtVal;
    // End of variables declaration//GEN-END:variables
}
