/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author Débora alves
 */
public class Genio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Genio.class.getName());

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
        Frase.setText("<html>Vou pensar em um valor entre 1 e 5. Tente adivinhar!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Valordigitado = new javax.swing.JSpinner();
        Palpite = new javax.swing.JButton();
        Frase = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/view/lamp.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/view/genie.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 82, 118));

        jLabel1.setText("Valor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 247, -1, -1));

        Valordigitado.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(Valordigitado, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 244, 52, -1));

        Palpite.setText("Palpite");
        Palpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(Palpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 272, -1, -1));

        Frase.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Frase.setForeground(new java.awt.Color(255, 255, 255));
        Frase.setText("Frase");
        getContentPane().add(Frase, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 140, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/view/speech-bubble (2).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalpiteActionPerformed
        // TODO add your handling code here:
    double n = 1 + Math.random() * (6 - 1);
    int valor = (int) n;
    
    int num = Integer.parseInt(Valordigitado.getValue().toString());
    
    String f1 = "<html>Parabéns, você acertou!!</html>";
    String f2 = "<html>Errou! Eu pensei no valor " + valor + "<html>";
    
    String res = (valor == num)?f1:f2;
    
    Frase.setText(res);
    }//GEN-LAST:event_PalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Genio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Frase;
    private javax.swing.JButton Palpite;
    private javax.swing.JSpinner Valordigitado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
